[package]
description = "Ethereum engine trai definition"
name = "engine"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
builtin = { path = "../builtin", package = "ethcore-builtin" }
ethereum-types = "0.6.0"
ethkey = { path = "../../accounts/ethkey" }
machine = { path = "../machine" }
bytes = { package = "parity-bytes", version = "0.1.0" }
vm = { path = "../vm" }


